In [2]:
import pandas as pd
df=pd.read_csv('data1.csv')
df.head()

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,2/25/2022,"['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,12/10/2019,['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,3/3/2017,"['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,9/15/2015,"['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,2/24/2017,['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K

In [3]:
import pandas as pd
df=pd.read_csv('data2.csv')
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [4]:
#remove duplicates in data1
df=pd.read_csv('data1.csv')
df_clean=df.drop_duplicates()
df_clean.to_csv('o1.csv', index=False)
print("Duplicate removed successfully")

Duplicate removed successfully

In [5]:
df=pd.read_csv('o1.csv')
df.head()

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,2/25/2022,"['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,12/10/2019,['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,3/3/2017,"['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,9/15/2015,"['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,2/24/2017,['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K

In [6]:
df.to_csv("o1.csv", index=False)

In [7]:
#remove duplicates in data2
df=pd.read_csv('data2.csv')
df_clean=df.drop_duplicates()
df_clean.to_csv('o2.csv', index=False)
print("Duplicate removed successfully")

Duplicate removed successfully

In [8]:
df=pd.read_csv('o2.csv')
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [9]:
df.to_csv("o2.csv", index=False)
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [10]:
df=pd.read_csv('o1.csv')
df.isnull().values.any()

np.True_

In [11]:
df[df.isnull().any(axis=1)]

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
587,587,Final Fantasy XVI,6/22/2023,"['Square Enix', 'Square Enix Creative Business...",NaN,422,422,['RPG'],Final Fantasy XVI is an upcoming action role-p...,[],37,10,732,2.4K
649,649,Death Stranding 2,releases on TBD,['Kojima Productions'],NaN,105,105,"['Adventure', 'Shooter']",NaN,[],3,0,209,644
713,713,Final Fantasy VII Rebirth,12/31/2023,['Square Enix'],NaN,192,192,[],This next standalone chapter in the FINAL FANT...,[],20,3,354,1.1K
719,719,Lies of P,8/1/2023,"['NEOWIZ', 'Round8 Studio']",NaN,175,175,['RPG'],"Inspired by the familiar story of Pinocchio, L...",[],5,0,260,939
726,726,Judas,3/31/2025,['Ghost Story Games'],NaN,90,90,"['Adventure', 'Shooter']",A disintegrating starship. A desperate escape ...,[],1,0,92,437
746,746,Like a Dragon Gaiden: The Man Who Erased His Name,12/31/2023,"['Ryū Ga Gotoku Studios', 'Sega']",NaN,118,118,"['Adventure', 'Brawler', 'RPG']",This game covers Kiryu's story between Yakuza ...,[],2,1,145,588
972,972,The Legend of Zelda: Tears of the Kingdom,5/12/2023,"['Nintendo', 'Nintendo EPD Production Group No...",NaN,581,581,"['Adventure', 'RPG']",The Legend of Zelda: Tears of the Kingdom is t...,[],72,6,1.6K,5.4K
1130,1130,Star Wars Jedi: Survivor,4/28/2023,"['Respawn Entertainment', 'Electronic Arts']",NaN,250,250,['Adventure'],The story of Cal Kestis continues in Star Wars...,[],13,2,367,1.4K
1160,1160,We Love Katamari Reroll + Royal Reverie,6/2/2023,"['Bandai Namco Entertainment', 'MONKEYCRAFT Co...",NaN,51,51,"['Adventure', 'Puzzle']",We Love Katamari Reroll + Royal Reverie is a r...,[],3,0,74,291
1202,1202,Earthblade,12/31/2024,['Extremely OK Games'],NaN,83,83,"['Adventure', 'Indie', 'RPG']","You are Névoa, an enigmatic child of Fate retu...",[],0,1,103,529
1245,1245,NEET Girl Date Night,10/21/2022,NaN,2.7,21,21,['Visual Novel'],Your friend sets you up on a date with his NEE...,"['this sucked. ""Omg she is literally me"" is no...",106,1,44,42
1305,1305,Diablo IV,6/6/2023,['Blizzard Entertainment'],NaN,148,148,"['Brawler', 'RPG']",Endless demons to slaughter. Deep customizatio...,[],19,10,179,677
1341,1341,Pac-Man in a Tin,3/22/2023,['Fizz Creations'],NaN,0,0,['Arcade'],Pac-Man in a Tin is a pocket-sized tin contain...,[],1,0,1,2
1349,1349,Pokémon Añil,3/23/2023,['Eric Lost'],NaN,2,2,['RPG'],Pokémon Añil is the fourth video game created ...,"['pokemon HWHAT', 'Finally, after all these ye...",1,0,1,7

In [12]:
df=pd.read_csv('o1.csv')
df['Team'] = df['Team'].fillna("No Team")
df[df.isnull().any(axis=1)]

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
587,587,Final Fantasy XVI,6/22/2023,"['Square Enix', 'Square Enix Creative Business...",NaN,422,422,['RPG'],Final Fantasy XVI is an upcoming action role-p...,[],37,10,732,2.4K
649,649,Death Stranding 2,releases on TBD,['Kojima Productions'],NaN,105,105,"['Adventure', 'Shooter']",NaN,[],3,0,209,644
713,713,Final Fantasy VII Rebirth,12/31/2023,['Square Enix'],NaN,192,192,[],This next standalone chapter in the FINAL FANT...,[],20,3,354,1.1K
719,719,Lies of P,8/1/2023,"['NEOWIZ', 'Round8 Studio']",NaN,175,175,['RPG'],"Inspired by the familiar story of Pinocchio, L...",[],5,0,260,939
726,726,Judas,3/31/2025,['Ghost Story Games'],NaN,90,90,"['Adventure', 'Shooter']",A disintegrating starship. A desperate escape ...,[],1,0,92,437
746,746,Like a Dragon Gaiden: The Man Who Erased His Name,12/31/2023,"['Ryū Ga Gotoku Studios', 'Sega']",NaN,118,118,"['Adventure', 'Brawler', 'RPG']",This game covers Kiryu's story between Yakuza ...,[],2,1,145,588
972,972,The Legend of Zelda: Tears of the Kingdom,5/12/2023,"['Nintendo', 'Nintendo EPD Production Group No...",NaN,581,581,"['Adventure', 'RPG']",The Legend of Zelda: Tears of the Kingdom is t...,[],72,6,1.6K,5.4K
1130,1130,Star Wars Jedi: Survivor,4/28/2023,"['Respawn Entertainment', 'Electronic Arts']",NaN,250,250,['Adventure'],The story of Cal Kestis continues in Star Wars...,[],13,2,367,1.4K
1160,1160,We Love Katamari Reroll + Royal Reverie,6/2/2023,"['Bandai Namco Entertainment', 'MONKEYCRAFT Co...",NaN,51,51,"['Adventure', 'Puzzle']",We Love Katamari Reroll + Royal Reverie is a r...,[],3,0,74,291
1202,1202,Earthblade,12/31/2024,['Extremely OK Games'],NaN,83,83,"['Adventure', 'Indie', 'RPG']","You are Névoa, an enigmatic child of Fate retu...",[],0,1,103,529
1305,1305,Diablo IV,6/6/2023,['Blizzard Entertainment'],NaN,148,148,"['Brawler', 'RPG']",Endless demons to slaughter. Deep customizatio...,[],19,10,179,677
1341,1341,Pac-Man in a Tin,3/22/2023,['Fizz Creations'],NaN,0,0,['Arcade'],Pac-Man in a Tin is a pocket-sized tin contain...,[],1,0,1,2
1349,1349,Pokémon Añil,3/23/2023,['Eric Lost'],NaN,2,2,['RPG'],Pokémon Añil is the fourth video game created ...,"['pokemon HWHAT', 'Finally, after all these ye...",1,0,1,7

In [13]:
df=pd.read_csv('o1.csv')
df['Rating'] = pd.to_numeric(
    df['Rating'],
    errors='coerce'
).round(1)

In [14]:
df['Rating'] = (
    pd.to_numeric(df['Rating'], errors='coerce')
      .fillna(0.0)
      .round(1)
)

In [15]:
df['Rating'].head()

0    4.5
1    4.3
2    4.4
3    4.2
4    4.4
Name: Rating, dtype: float64

In [16]:
df[df.isnull().any(axis=1)]

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
649,649,Death Stranding 2,releases on TBD,['Kojima Productions'],0.0,105,105,"['Adventure', 'Shooter']",NaN,[],3,0,209,644
1245,1245,NEET Girl Date Night,10/21/2022,NaN,2.7,21,21,['Visual Novel'],Your friend sets you up on a date with his NEE...,"['this sucked. ""Omg she is literally me"" is no...",106,1,44,42

In [17]:
df['Summary'] = df['Summary'].fillna("No Summary")
df[df.isnull().any(axis=1)]

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
1245,1245,NEET Girl Date Night,10/21/2022,NaN,2.7,21,21,['Visual Novel'],Your friend sets you up on a date with his NEE...,"['this sucked. ""Omg she is literally me"" is no...",106,1,44,42

In [18]:
df.to_csv("o1.csv", index=False)

In [19]:
df=pd.read_csv('o2.csv')
df.isnull().values.any()

np.True_

In [20]:
df[df.isnull().any(axis=1)]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
179,180,Madden NFL 2004,PS2,NaN,Sports,Electronic Arts,4.26,0.26,0.01,0.71,5.23
377,378,FIFA Soccer 2004,PS2,NaN,Sports,Electronic Arts,0.59,2.36,0.04,0.51,3.49
431,432,LEGO Batman: The Videogame,Wii,NaN,Action,Warner Bros. Interactive Entertainment,1.86,1.02,0.00,0.29,3.17
470,471,wwe Smackdown vs. Raw 2006,PS2,NaN,Fighting,NaN,1.57,1.02,0.00,0.41,3.00
607,608,Space Invaders,2600,NaN,Shooter,Atari,2.36,0.14,0.00,0.03,2.53
...,...,...,...,...,...,...,...,...,...,...,...
16427,16430,Virtua Quest,GC,NaN,Role-Playing,Unknown,0.01,0.00,0.00,0.00,0.01
16493,16496,The Smurfs,3DS,NaN,Action,Unknown,0.00,0.01,0.00,0.00,0.01
16494,16497,Legends of Oz: Dorothy's Return,3DS,2014.0,Puzzle,NaN,0.00,0.01,0.00,0.00,0.01
16543,16546,Driving Simulator 2011,PC,2011.0,Racing,NaN,0.00,0.01,0.00,0.00,0.01
16553,16556,Bound By Flame,X360,2014.0,Role-Playing,NaN,0.00,0.01,0.00,0.00,0.01

In [21]:
df['Year'] = df['Year'].fillna(0).astype(int)
df['Publisher'] = df['Publisher'].fillna(0)

In [22]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Rank, Name, Platform, Year, Genre, Publisher, NA_Sales, EU_Sales, JP_Sales, Other_Sales, Global_Sales]
Index: []

In [23]:
df.to_csv("o2.csv", index=False)
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [24]:
df.head()

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

In [25]:
df.to_csv("o2.csv", index=False)

In [26]:
df=pd.read_csv('o1.csv')
print(df.columns.tolist())

['Unnamed: 0', 'Title', 'Release Date', 'Team', 'Rating', 'Times Listed', 'Number of Reviews', 'Genres', 'Summary', 'Reviews', 'Plays', 'Playing', 'Backlogs', 'Wishlist']

In [27]:
df=pd.read_csv('o1.csv')
df['Release Date'] = pd.to_datetime(df['Release Date'], errors='coerce')

# Standardize format
df['Release Date'] = df['Release Date'].dt.strftime("%Y-%m-%d")

In [28]:
df.head()

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,2022-02-25,"['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,2019-12-10,['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,2017-03-03,"['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,2015-09-15,"['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,2017-02-24,['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K

In [29]:
df.to_csv("o1.csv", index=False)

In [30]:
df.head()

,Unnamed: 0,Title,Release Date,Team,Rating,Times Listed,Number of Reviews,Genres,Summary,Reviews,Plays,Playing,Backlogs,Wishlist
0,0,Elden Ring,2022-02-25,"['Bandai Namco Entertainment', 'FromSoftware']",4.5,3.9K,3.9K,"['Adventure', 'RPG']","Elden Ring is a fantasy, action and open world...","[""The first playthrough of elden ring is one o...",17K,3.8K,4.6K,4.8K
1,1,Hades,2019-12-10,['Supergiant Games'],4.3,2.9K,2.9K,"['Adventure', 'Brawler', 'Indie', 'RPG']",A rogue-lite hack and slash dungeon crawler in...,['convinced this is a roguelike for people who...,21K,3.2K,6.3K,3.6K
2,2,The Legend of Zelda: Breath of the Wild,2017-03-03,"['Nintendo', 'Nintendo EPD Production Group No...",4.4,4.3K,4.3K,"['Adventure', 'RPG']",The Legend of Zelda: Breath of the Wild is the...,['This game is the game (that is not CS:GO) th...,30K,2.5K,5K,2.6K
3,3,Undertale,2015-09-15,"['tobyfox', '8-4']",4.2,3.5K,3.5K,"['Adventure', 'Indie', 'RPG', 'Turn Based Stra...","A small child falls into the Underground, wher...",['soundtrack is tied for #1 with nier automata...,28K,679,4.9K,1.8K
4,4,Hollow Knight,2017-02-24,['Team Cherry'],4.4,3K,3K,"['Adventure', 'Indie', 'Platform']",A 2D metroidvania with an emphasis on close co...,"[""this games worldbuilding is incredible, with...",21K,2.4K,8.3K,2.3K

In [31]:
df = pd.read_csv("o1.csv")

# Rename Column name
df.rename(columns={'Unnamed: 0': 'SL_NO',
                   'Release Date':'Release_Date',
                   'Times Listed': 'Times_Listed',
                   'Number of Reviews': 'Number_of_Reviews',
                  }, inplace=True)

In [32]:
df.drop(columns=['SL_NO'], inplace=True)

In [33]:
print(df.columns.tolist())

['Title', 'Release_Date', 'Team', 'Rating', 'Times_Listed', 'Number_of_Reviews', 'Genres', 'Summary', 'Reviews', 'Plays', 'Playing', 'Backlogs', 'Wishlist']

In [34]:
df.to_csv("o1.csv", index=False)

In [35]:
import numpy as np
df = pd.read_csv("o1.csv")
def convert_k(val):
    if pd.isna(val):
        return 0
    val = str(val).lower().strip()
    if val.endswith('k'):
        return int(float(val.replace('k', '')) * 1000)
    return int(float(val))

df['Times_Listed'] = df['Times_Listed'].apply(convert_k)

In [36]:
df['Times_Listed'].head()
df['Times_Listed'].dtype

dtype('int64')

In [37]:
import pandas as pd

def clean_reviews(val):
    if pd.isna(val):
        return 0
    val = str(val).lower().strip()

    if val.endswith('k'):
        return int(float(val.replace('k', '')) * 1000)

    if val.endswith('m'):
        return int(float(val.replace('m', '')) * 1_000_000)

    val = val.replace(',', '')
    return int(float(val)) if val.replace('.', '').isdigit() else 0

df['Number_of_Reviews'] = df['Number_of_Reviews'].apply(clean_reviews)

In [38]:
print(df['Number_of_Reviews'].head(10))
print(df['Number_of_Reviews'].dtype)
print(df['Number_of_Reviews'].max())

0    3900
1    2900
2    4300
3    3500
4    3000
5    2300
6    1600
7    2100
8     867
9    2900
Name: Number_of_Reviews, dtype: int64
int64
4300

In [39]:
import numpy as np

def convert_k(val):
    if pd.isna(val):
        return 0
    val = str(val).lower().strip()
    if val.endswith('k'):
        return int(float(val.replace('k', '')) * 1000)
    return int(float(val))

df['Plays'] = df['Plays'].apply(convert_k)

In [40]:
import numpy as np

def convert_k(val):
    if pd.isna(val):
        return 0
    val = str(val).lower().strip()
    if val.endswith('k'):
        return int(float(val.replace('k', '')) * 1000)
    return int(float(val))

df['Playing'] = df['Playing'].apply(convert_k)

In [41]:
import numpy as np

def convert_k(val):
    if pd.isna(val):
        return 0
    val = str(val).lower().strip()
    if val.endswith('k'):
        return int(float(val.replace('k', '')) * 1000)
    return int(float(val))

df['Backlogs'] = df['Backlogs'].apply(convert_k)

In [42]:
import numpy as np

def convert_k(val):
    if pd.isna(val):
        return 0
    val = str(val).lower().strip()
    if val.endswith('k'):
        return int(float(val.replace('k', '')) * 1000)
    return int(float(val))

df['Wishlist'] = df['Wishlist'].apply(convert_k)

In [43]:
df.to_csv("o1.csv", index=False)

In [44]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\dell\anaconda3\lib\site-packages (1.1.2)

In [45]:
import pymysql
print(pymysql.__version__)

1.4.6

In [2]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("o1.csv")

# 3. Create MySQL connection
engine = create_engine(
    "mysql+pymysql://root:$Suhan143@localhost:3306/game_data")

    # 4. Load data into MySQL table
df.to_sql(
    name='game_data',
    con=engine,
    if_exists='append',
    index=False
)

print("Data loaded successfully into MySQL")

Data loaded successfully into MySQL

In [47]:
df = pd.read_csv('o2.csv')

In [48]:
print(df.columns.tolist())

['Rank', 'Name', 'Platform', 'Year', 'Genre', 'Publisher', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']

In [55]:
#loading o2.csv to sql
df = pd.read_csv('o2.csv')

# Rename Column name
df.rename(columns={'Rank': 'Rank_',
                   'Name':'Name_',
                   'Year': 'Year_',
                   'Na_Sales': 'Na_sales',
                   'Eu_Sales': 'Eu_sales',
                   'Jp_Sales': 'Jp_sales',
                   'Other_Sales': 'Other_sales',
                   'Global_Sales': 'Global_sales'
                  }, inplace=True)

In [56]:
print(df.columns.tolist())

['Rank_', 'Name_', 'Platform', 'Year_', 'Genre', 'Publisher', 'NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_sales', 'Global_sales']

In [57]:
df.to_csv("o2.csv", index=False)

In [58]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\dell\anaconda3\lib\site-packages (1.1.2)

In [59]:
import pymysql
print(pymysql.__version__)

1.4.6

In [4]:
import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("o2.csv")

# 3. Create MySQL connection
engine = create_engine(
    "mysql+pymysql://root:$Suhan143@localhost:3306/game_data")

    # 4. Load data into MySQL table
df.to_sql(
    name='game_sales',
    con=engine,
    if_exists='append',
    index=False
)

print("Data loaded successfully into MySQL")

Data loaded successfully into MySQL

In [2]:
import pandas as pd

# Load dataset
df = pd.read_csv("o1.csv")
# Filter games with at least 100 reviews
filtered_df = df[df['Number_of_Reviews'] >= 100]

# Sort by rating
top_games = filtered_df.sort_values(by="Rating", ascending=False)

print(top_games[['Title', 'Rating', 'Number_of_Reviews']].head(10))

                                         Title  Rating  Number_of_Reviews
428                              Disco Elysium     4.6               1100
991            Metal Gear Solid 3: Subsistence     4.6                641
28                Disco Elysium: The Final Cut     4.6               1100
957               Final Fantasy XIV: Endwalker     4.6                426
1090         The Great Ace Attorney 2: Resolve     4.6                386
894                              Disco Elysium     4.6               1100
1104  Sekiro: Shadows Die Twice - GOTY Edition     4.6                173
1138                           Half-Life: Alyx     4.6                515
1035               Bloodborne: The Old Hunters     4.6                266
539               Umineko: When They Cry Chiru     4.6                324

In [6]:
import pandas as pd

df = pd.read_csv("album.csv", encoding="utf-8", encoding_errors="replace")
df.to_csv("album.csv", index=False, encoding="utf-8-sig")

In [7]:
with open("album.csv", "rb") as f:
    data = f.read()
print(data.find(b'\x81'))

6073

In [10]:
import pandas as pd

with open("album.csv", "rb") as f:
    data = f.read()

data = data.replace(b'\x81', b'')

with open("album2.csv", "wb") as f:
    f.write(data)